language: python

addons:
    chrome: stable

python:
    - "3.6"

services:
    - postgresql

install:
    - pip install -r requirements.txt
    - pip install -r dev_requirements.txt
    - wget -N http://chromedriver.storage.googleapis.com/2.33/chromedriver_linux64.zip -P ~/
    - unzip ~/chromedriver_linux64.zip -d ~/
    - rm ~/chromedriver_linux64.zip
    - sudo mv -f ~/chromedriver /usr/local/share/
    - sudo chmod +x /usr/local/share/chromedriver
    - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

before_script:
    - psql -c "CREATE ROLE osschallenge CREATEDB LOGIN PASSWORD 'osschallenge';" -U postgres
    - psql -c "CREATE DATABASE osschallenge;" -U postgres

script: 
    - docker-compose up -d --build
    - docker-compose ps
    - docker-compose run osschallenge coverage run manage.py test osschallenge/tests

after_success:
    - bash <(curl -s https://codecov.io/bash)
